### ISSUE TITLE
👉Auth0

### ISSUE THREAD

**Issue by woloski** [bafrontend/trabajos#10]
We're looking for people who care deeply about quality, team work and want to build software that people love.
- We believe in crafted software, in end-to-end ownership of projects and hyper-fast iterations.
- We like to write about things we solve and how.
- We like to contribute back to the community, often by building things we think are cool and by releasing open-source software ([passportjs](https://passportjs.org), [limitd](https://github.com/auth0/limitd), [sharelock](https://sharelock.io), [JWT](http://jwt.io))
- We launch anything we do as early as we can. We want to ensure that we're building what users actually want.

And we are just starting, there are tons of things on our roadmap that you could help us with.

Front End Engineers 👉https://auth0.com/jobs/engineer
# About Auth0

We want to be the authentication component on every application in the world. Just like Twilio does for communications or Sendgrid for e-mails or Stripe for payments.
- We're a startup, with main HQs in Seattle and Buenos Aires (Palermo). 
- We've grown to 40 people in two years. 
- We make money selling our software as a service
- We are backed by [Bessemer Venture Partners](bvp.com) (investors of Twilio, Sendgrid, Shopify, among others).
- We embrace distributed work, we give you a MacBook Pro Retina latest spec, healthcare, equity and above average salary.

**Comment by pazguille** [comment]
@woloski Estamos ordenando el repositorio de búsquedas. Esta sigue vigente?
