### ISSUE TITLE
Front End Developer - GlobalLogic

### ISSUE THREAD

**Issue by lucianaloioco** [bafrontend/trabajos#11]
GlobalLogic, compañía multinacional líder en Servicios de I+D esta buscando un Developer Front end Sr para sumar a un nuevo proyecto para un importante cliente de Estados Unidos

 

Requisitos excluyentes:

JavaScript orientado a objetos
HTML 5 
Angular JS
Inglés avanzado (conversación fluida)
Brindamos:

Certificaciones a cargo de la empresa.
Cursos de inglés in-company.
Programas permanentes de entrenamiento y desarrollo.
Excelente clima laboral y un espacio propicio para el crecimiento profesional.
Participación en los proyectos más desafiantes y en equipos multidisciplinarios.
Obra social de primera calidad.
Home office.
Si querés desarrollar tu carrera en una empresa líder en el desarrollo de productos de software y participar en proyectos desafiantes de primera línea a nivel internacional ¡Sumate a nuestro equipo!

Envianos tu CV a: luciana.loioco@globallogic.com sin omitir remuneración pretendida

Lugar de trabajo: Capital Federal, Buenos Aires / La Plata / Mendoza

**Comment by pazguille** [comment]
@lucianaloioco Estamos ordenando el repositorio de búsquedas. Esta sigue vigente?
