### ISSUE TITLE
Interaction Designer - Conrad Caine

### ISSUE THREAD

**Issue by PabloAlaejos** [bafrontend/trabajos#13]
Reports to: Interface Concept Director (Munich Office)

Conrad Caine is looking for a talented Interaction Designer that is passionate about developing information architecture and has a good grasp of current wireframing tools for creating digital experiences. 

Your tasks
− Idea generation for innovative concepts for web and mobile
− Development of information architecture and a user-orientated navigation concepts
− Creation of basic and detailed concepts in the form of sitemaps and use cases as well as wireframes
− Support of concept presentations

Required soft skills and experience
− Good knowledge in usability and user experience
− Highly developed creativity and highest quality standards
− Readiness to learn and quick-witted
− Process-orientated
− Good knowledge in the current wireframing tools
− Good command of English

If you are seeking an international company, interesting projects, and a harmonious working atmosphere, apply to busquedas@conrad-caine.com with “Interaction Designer” in the subject line.

**Comment by pazguille** [comment]
@PabloAlaejos Estamos ordenando el repositorio de búsquedas. Esta sigue vigente?
