### ISSUE TITLE
UI/UX designer @ DemocracyOS

### ISSUE THREAD

**Issue by gvilarino** [bafrontend/trabajos#14]
We're looking for a **UI/UX Designer** to help us conceive the future of citizen participation.

If you're passionate about building meaningful experiences with deep, global, social and civic impact, our team needs you!

The opening is for a full-time job in our offices in Palermo, Buenos Aires and you'll be working on our core project, DemocracyOS, as well as our other projects and websites.

We love to prototype, build, measure and learn, so wireframing and blueprinting with whichever tools you love (we love `Sketch`!) is something you'll be doing a lot.

Since you'll be joining the core development team, deep knowledge on `CSS` (we mostly use `stylus`, but it's ok if you don't) and `HTML` (`Jade` is even better!) is a must.

Also, we serve different users with different devices, so your designs *must* be fully responsive.

If you also code in `JavaScript`, then `<3 ++`

### About us

We're a non-profit organisation based in Buenos Aires, Argentina with a mission to make politics smarter by bringing Democracy to the 21st century.

We work with all sorts of organisations, from government agencies to political parties, to small activist groups all around the world.

We've recently been through [YCombinator](http://www.ycombinator.com/) and are backed by many international philanthropic organisations like [Avina](http://www.avina.net/), [Open Knowledge Foundation](https://okfn.org/), the [World Justice Project](http://worldjusticeproject.org/), among others.

We are [100% open source](https://github.com/DemocracyOS) and *will always stay that way*. We also have a habit of giving back to the Open Source community either by collaborating on other OSS projects, or by joining international hackathons related to Open Data initiatives, civic hacking, and the like. Our development community is large and strong, and our main repo has over 900 stars and 300 forks, as well as available in over 15 languages.

### Join us!

If you want to join our voyage and help is in finding out how the future of Democracy looks and feels like, please shoot us an email: [guido@democracyos.org](mailto:guido@democracyos.org)

Learn more about us on [our website](http://democracyos.org)

**Comment by pazguille** [comment]
@gvilarino Estamos ordenando el repositorio de búsquedas. Esta sigue vigente?

**Comment by gvilarino** [comment]
Justo este miércoles arrancó el nuevo diseñador así que justo a tiempo! Lo cierro. Gracias!
