### ISSUE TITLE
QA Analyst - Pixel2HTML

### ISSUE THREAD

**Issue by argen** [bafrontend/trabajos#15]
Hello there! We're looking to add a new person in our _QA Team_, please take a look at the following requirements for the job:

You must have knowledge in the following areas of expertise:
- HTML5/CSS3
- Pre-processors: SASS/LESS
- JavaScript Medium/Advanced
- GIT Knowledge (Mandatory)
- WordPress CMS Basics
- Experience working on a distributed and fast moving team
- Knowledgeable about popular web/mobile browsers (Internet Explorer, Firefox, Safari, etc.)
- Familiarity with issue tracking tools (Gitlab Issues, JIRA, Bugzilla, etc.)
- Great English Communication skills (Oral/Written)

Also nice to have:
- Jade/Stylus
- Gulp/Grunt Task automators
- PHP/Ruby/NodeJs backend coding knowledge
- Experience with automated load testing tools (ex. Selenium, PhantomJS)
- Another languages (Spanish, Portuguese, French) are a plus!

Note: this position is to work remotely!

If you think you you match this requirements, feel free to shoot us an email to contact@pixel2html.com with the _"QA Analyst"_ title on the subject. We look forward meeting you and working together soon :)

**Pixel2HTML** is a _FrontEnd Development_ company specialised in Pixel to HTML/CSS conversions with more than 5 years in the market serving more than 900 clients around the globe. We focus on prompt deliveries, astonishing quality and a great customer service.

**Comment by pazguille** [comment]
@argen Estamos ordenando el repositorio de búsquedas. Esta sigue vigente?
