### ISSUE TITLE
Profesor/a JavaScript 🎓 | Acamica.com

### ISSUE THREAD

**Issue by gonzaloorsi** [bafrontend/trabajos#18]
----
#### Nuestra misión es crear el talento del futuro ¿Querés ayudar?
----
###### Full Time, Buenos Aires, Argentina

Los postulantes deberán trabajar desde las oficina de Acamica en Buenos Aires.

Estamos buscando un profesor/a de JavaScript con amplia experiencia en la creación de aplicaciones web. Como profesor/a de Acamica, se unirán a un divertido equipo de profesores y crearán material educativo de altísima calidad para los estudiantes de Acamica. Deberán ser personas motivadas para aprender las últimas técnicas y tendencias de la industria web y disfrutar de compartir conocimientos con otros. Deberán ser grandes presentadores/as y que les apasione estar frente a la cámara para explicar conceptos difíciles de forma fácil.

##### Responsabilidades

- Trabajar conjuntamente a otros profesores/as en el diseño de la currícula de Acamica identificando temas que son cruciales hoy para los trabajos en la industria tecnológica.
- Escribir contenido educativo y trabajar con el equipo de producción. Esto incluye:
    - Escribir guiones.
    - Crear proyectos didácticos que incluyen aplicaciones JS.
    - Crear material de evaluación usando los desafíos y exámenes de Acamica.
    - Grabar el material de los cursos en el set de producción como también a través de screencast.

- Explorar nuevas librerías JS.
- Revisar cursos para mantenerlos actualizarlos con las últimas herramientas.
- Soporte en el foro para responder preguntas específicas de los a estudiantes.

##### Perfil

- Amar el desarrollo, enseñar y aprender.
- Tener el deseo de cambiarle la vida a las personas enseñandoles habilidades aplicadas para los trabajos de hoy.
- Buenas habilidades de escritura.
- Excelente capacidad de presentación y confianza frente a la cámara.
- Organizado/a y orientado/a al trabajo en proyectos.
- Demostrar habilidades de desarrollo JS con entendimiento de:  

    - AngularJS
    - Node.js
    - Socket.io
    - TypeScript
    - MongoDB

- Excelentes conocimientos de:
    - JavaScript

##### Beneficios

Como extra de sumarse a un empresa innovadora y trabajar en un equipo que considera que el equipo lo es todo, también tendrán:

- 3 semanas de vacaciones.
- Capacitación constante.
- Entradas para eventos/conferencias de tecnología.

⚡️ Aplicá directamente en https://acamica.hiretracking.com ⚡️

**Comment by pazguille** [comment]
@gonzaloorsi Estamos ordenando el repositorio de búsquedas. Esta sigue vigente?

**Comment by gonzaloorsi** [comment]
Guille, cómo estás? Gracias por preguntar. No, cerrada.
