### ISSUE TITLE
Desarrollador Web Front-End @Aerolab

### ISSUE THREAD

**Issue by sbehrends** [bafrontend/trabajos#2]
You can’t buy happiness, but we have coffee & that’s pretty close.

Te estamos buscando para desarrollar proyectos innovadores, trabajando a la par con diseñadores top notch. Nos gustaría que propongas, seas curioso, experimentes, busques superarte en cada nuevo desafío y que estés en constante cambio (no de peinado, sino de tecnología). A cambio, te ofrecemos un hacker desk, 2 monitores, una máquina bestial, mucho café, la libertad de manejar el software que creas conveniente y diferentes dispositivos (con iOS y Android) para que puedas probar cómo se ve tu creación en todas las plataformas.

https://aerolab.hiretracking.com/aerolab/job/10117

**Comment by pazguille** [comment]
@sbehrends Estamos ordenando el repositorio de búsquedas. Esta sigue vigente?
