### ISSUE TITLE
Busco clases html css js via skype

### ISSUE THREAD

**Issue by rcp-sph** [bafrontend/trabajos#20]
Estoy buscando alguien dispuesto a darme clases sobre todo js via skype. Seria por el momento una o dos veces por semana. La idea es tomar alguna proyecto simple e ir haciendo juntos. Tengo particular interés en data viz y d3.js. Ademas de las clases seguramente saldran sobre la marcha proyectos freelance.
Les dejo mi contacto rcp.shp@gmail.com

Saludos

**Comment by pazguille** [comment]
@rcp-sph Estamos ordenando el repositorio de búsquedas. Esta sigue vigente?
