### ISSUE TITLE
Front-end Developers proyectos en Magento

### ISSUE THREAD

**Issue by HRSummaSolutions** [bafrontend/trabajos#21]
Summa Solutions incorpora Front-end Developers para proyectos de E-commerce para distintas partes del mundo. Tenemos oficina en Palermo y Tandil.
Requerimos que cuentes con  sólidos conocimientos en HTML5, CSS3,  JavaScript y Jquery. Por supuesto que cuentes con experiencia en Photoshop e Illustrator. También con conocimientos en DOM, AJAX y JSON. Si trabajás con SASS o LESS, mucho mejor.
Es ideal que sepas PHP y sobretodo Programación Orientada a Objetos. También que utilices algún sistema de control, preferentemente GIT.
Es ideal que cuentes buen nivel de inglés conversacional.

Si te interesa esta propuesta escribime a: mmuras@summasolutions.net Ref: Front-end

**Comment by pazguille** [comment]
@HRSummaSolutions Estamos ordenando el repositorio de búsquedas. Esta sigue vigente?

**Comment by pazguille** [comment]
@HRSummaSolutions Estamos ordenando el repositorio de búsquedas. Esta sigue vigente?
