### ISSUE TITLE
Full-Stack Web Developer | Rodati | Buenos Aires

### ISSUE THREAD

**Issue by lucia-rodati** [bafrontend/trabajos#22]
Hola!

En Rodati estamos buscando un Full Stack Web Developer para trabajar en nuestro equipo de Development en Buenos Aires.

¿Quiénes somos?
Somos un startup nacido en Argentina, con oficinas en Buenos Aires y Brasil. Tenemos operaciones en la ciudad São Paulo, y el objetivo de ser la empresa líder de venta de autos en Latinoamérica. Contamos con el apoyo de los principales grupos inversores de la región: Quasar Ventures, Emergence Capital, Richmond Global, NXTP Ventures, entre otros fondos.
Somos un equipo joven de 40 emprendedores que ayudan a cientos de personas a realizar su sueño de tener un auto, dándoles la mejor experiencia de compra. Somos innovadores, divertidos y flexibles. Creamos nuestras propias reglas sobre cómo debe ser un negocio. Somos gente de acción, expeditivos, que resuelven las cosas sin miedo a los retos. Somos proactivos e independientes. No creemos en trabajos aburridos y tediosos, pero sí en hacer cosas que tengan MUCHO impacto. Estamos interesados ​​en personas motivadas por crecer y desarrollarse.

¿Cuales son las responsabilidades principales de este rol?
•  Trabajar junto a nuestro equipo altamente calificado en el desarrollo integral de la plataforma de rodati.com.
•  Ayudar en la definición de los procesos de desarrollo, arquitecturas y metodologías que utilizará el equipo y las aplicaciones.
•  Investigar, diseñar y crear los componentes desacoplados que conforman a rodati.com así como sus herramientas accesorias.
•  Cuando se requiera, no debes tener problema en trabajar tanto en el front-end como en el back-end.
•  A mediano plazo, desarrollar las aplicaciones nativas para plataformas mobiles.

¿Qué tipo de persona estamos buscando?
Alguien que:
•  Tenga alguna experiencia demostrable y creíble en proyectos web de mediano o gran tamaño, ayudando tanto en el desarrollo client-side y server-side.
•  Tenga conocimientos de tecnologías de front-end y herramientas que agilicen el proceso de codificación y desarrollo.
•  Tenga experiencia con motores SQL y/o NoSQL.
•  Utilice herramientas de continuous delivery, continuous integration y testing.
•  Haya trabajado con metodologías ágiles.
•  Sea proactivo
•  Le guste trabajar en equipo

¿Qué conocimientos y habilidades adicionales nos interesan?
•  No nos interesa si toda tu vida trabajaste o tuviste como preferencia un lenguaje de programación particular, entendemos que todos los lenguajes trabajan con los mismos principios, patrones y herramientas.
•  Nuestra plataforma utiliza en su mayor parte JavaScript, tanto del lado del servidor como en el cliente, por lo cual si ya tenes experiencia en ese lenguaje es un plus.
•  Idioma portugués (no excluyente).

¿Qué beneficios ofrecemos?
•  Salario competitivo.
•  Plan Médico (OSDE).
•  Un ambiente de trabajo divertido (conocé más en http://instagram.com/rodatilife)
•  La oportunidad de ser parte de un startup con muchísimo potencial y un gran equipo. 

¿Cómo aplicar?
Llená este formulario: http://goo.gl/forms/kWG2SNkFtK y vamos a estar contactándote cuanto antes.

¿Qué otros puestos hay disponibles?
Entrá a http://careers.rodati.com y mirá todo el talento que estamos buscando en Rodati.

**Comment by pazguille** [comment]
@lucia-rodati Estamos ordenando el repositorio de búsquedas. Esta sigue vigente?
