### ISSUE TITLE
QA/QC :: @Flowics

### ISSUE THREAD

**Issue by angiesantaliz** [bafrontend/trabajos#23]
En Flowics estamos sumando gente al equipo de Desarrollo en el rol de Quality Control & Testing. 
Vas a tener la oportunidad de trabajar con un excelente equipo de desarrollo de producto, siendo el responsable de que éste funcione de acuerdo con los requisitos, trabaje con sus interfaces de la forma esperada, detectando en forma temprana defectos y evitando su propagación y llegada al cliente. 

Qué vas a hacer? 
- Diseñar y definir el plan de testing.
- Definir los casos de prueba en base a los requisitos funcionales, no funcionales y técnicos.
- Definir las pruebas de integración que se realizarán.
- Gestionar el armado de ambientes de prueba.
- Generar datos o lotes de prueba.
- Ejecutar los casos de prueba.
- Realizar la documentación de las pruebas (evidencia).
- Registrar los incidentes en la base a los defectos encontrados, así como realizar su seguimiento para asegurarse su adecuada corrección.
- Analizar y reportar los resultados de las pruebas, estadísticas, etc.

Qué necesitamos de vos?
- Que tengas experiencia haciendo Testing en Desarrollo de Software.
- Que conozcas metodologías y modelos de calidad para la industria del software.
- Que estés familiarizado con metodologías ágiles
- Que conozcas herramientas para la ejecución y seguimiento de testing.
- Que tengas conocimiento de diferentes Tipos de Testing
- Capacidad para medir el desempeño del producto.
- Que tengas un nivel intermedio de inglés, como para mantener una conversación.

Qué otras cosas pueden destacar tu perfil? 
- Que hayas estudiado Sistemas o Informática, o lo estés haciendo. 
- Que tengas experiencia en Automatización.
- Que seas detallista y tengas pensamiento analítico.
- Que tengas un don para las relaciones interpersonales.
- Que te enfoques en el cliente y la experiencia que va a tener usando nuestro producto, tanto interno como externo.
- Facilidad para incorporar y asimilar rápidamente nuestro producto

Conocenos mejor en www.flowics.com, y mandanos tu CV a jobs@flowics.com

![we are hiring and you will love it](https://cloud.githubusercontent.com/assets/7386056/10110904/9f0acc48-63a6-11e5-9e6e-0e14d5a0df87.jpg)

**Comment by pazguille** [comment]
@angiesantaliz Estamos ordenando el repositorio de búsquedas. Esta sigue vigente?
