### ISSUE TITLE
Frontend developer (preferentemente Angular)

### ISSUE THREAD

**Issue by f0go** [bafrontend/trabajos#24]
En Iamat estamos buscando un dev javascript frontend preferentemente con conocimientos de Angular aun que no es excluyente. Trabajamos con television y eventos como El Trece TV, Gran Hermano, Futbol Para Todos, C5N, Cocineros Argentinos y muchos más. 

Para destacar el clima de laburo es muy bueno!

**Comment by jaclar** [comment]
**Dato importante:** interesados por favor manden mail a lars@iamat.com

**Comment by pazguille** [comment]
@f0go Estamos ordenando el repositorio de búsquedas. Esta sigue vigente?

**Comment by f0go** [comment]
@pazguille No, ya fue cubierto el puesto.
