### ISSUE TITLE
Full-stack Web Developer | QuadMinds

### ISSUE THREAD

**Issue by pettinarip** [bafrontend/trabajos#25]
QuadMinds, empresa de tecnología IoT ubicada en Palermo, incorpora.

Para integrar el equipo de desarrollo de la plataforma de la empresa y proyectos específicos para clientes.

Perfil requerido:

* Manejo de PHP, MySQL, JavaScript y HTML 5.
* Interés en nuevas tecnologías como Node.js y AngularJS.
* Se valorarán conocimientos de Bootstrap y jQuery.
* La modalidad de contratación es de lunes a viernes de 9 a 18 Hs, presencial. Se ofrecen beneficios al empleado tales como: Cobertura médica, seguro, comedor a cargo de la empresa, excelente ambiente de trabajo.

Interesados enviar mail a: rrhh@quadminds.com , mencionando en el asunto Ref.: Desarrollador Web.  Indicar remuneración pretendida y referencias de desarrollos realizados.

**Comment by pazguille** [comment]
@pettinarip Estamos ordenando el repositorio de búsquedas. Esta sigue vigente?

**Comment by pettinarip** [comment]
No, dejalo afuera por el momento.
