### ISSUE TITLE
FrontEnd Dev @Flowics - DataViz

### ISSUE THREAD

**Issue by angiesantaliz** [bafrontend/trabajos#26]
En Flowics estamos sumando un Dev FrontEnd al equipo de Creative Services para trabajar con visualizacion de datos y contenido de redes sociales, creando experiencias digitales y experimentos. Si querés conocer más, acá podes visitar el Job Posting: http://goo.gl/kKj7Cy
Para conocer más escribime a angeles@flowics.com

![cr8wcsuu8aak9cz](https://cloud.githubusercontent.com/assets/7386056/10737714/77482566-7bf2-11e5-8756-eb1bfdd81667.png)

**Comment by pazguille** [comment]
@angiesantaliz Estamos ordenando el repositorio de búsquedas. Esta sigue vigente?
