### ISSUE TITLE
Busco freelance frontend developer

### ISSUE THREAD

**Issue by juanme** [bafrontend/trabajos#48]
Estoy buscando una desarrollador freelance (frontend) que tenga conocimientos avanzados, principalmente, en javascript, jquery, LESS / SASS y en lo posible frameworks como Angular.

Es muy importante que tenga muy buena experiencia. 

Saludos!

**Comment by osalas891123** [comment]
Como puedo optar por el puesto

**Comment by danielnaranjo** [comment]
Hola @juanme , que necesitas desarrollar?

**Comment by juanme** [comment]
Hola, gracias por la respuestas. Este es un issue bastante viejo que nos quedó sin cerrar. Disculpen la molestia. Saludos!
