### ISSUE TITLE
BUSCADO! Front end dev

### ISSUE THREAD

**Issue by sefod** [bafrontend/trabajos#5]
En ifstudio.co buscamos un Fron-end Semi-sr/senior que la tenga MUY CLARA (HTML Semántico, CSS3 & Media queries, Crossbrowser, js/jQuery. Comprobable) y que sepa usar WordPress para probar freelance con algunos proyectos y, si está interesado, quedar fijo. Tenemos muchos proyectos copados para hacer.
Si hay algún interesado me puede responder acá o mail a serafin ( a ) ifstudio.co 
Graciass!

**Comment by dientuki** [comment]
Hola, soy Front senior, actualmente estoy trabajando en TN (hice el front y soy encargado del front del sitio desktop y mobile), hice wordpress (tanto front como back), tengo un [plugin publicado]https://wordpress.org/plugins/simple-post-status-notifications/). Maquete el sitio de davinci y algunos mas.
Estoy disponible para trabajos de wordpress y/o maquetados freelance.

Saludos!

[Linkedin](https://ar.linkedin.com/pub/juan-alberto-farias/16/5b7/510)

**Comment by pazguille** [comment]
@sefod Estamos ordenando el repositorio de búsquedas. Esta sigue vigente?
