### ISSUE TITLE
Front-end en Antena

### ISSUE THREAD

**Issue by monsieurBelbo** [bafrontend/trabajos#9]
Estamos buscando a un desarrollador front-end con talento y ganas para sumarse al equipo de Antena. Somos un startup desarrollando tecnologías para mejorar y unificar la experiencia en salud.

Los candidatos deberán poder desarrollar sólidas arquitecturas de front-end que integren con otros sistemas y tecnologías, tener habilidades en el desarrollo de experiencias de usuario y usabilidad, poder optimizar la performance de una aplicación de front-end y poder trabajar con diseñadores y desarrolladores back-end.

Si te interesa trabajar en un ambiente distendido en una cómoda oficina desarrollando aplicaciones para mejorar la salud de todos, escribimos a jobs@antena.co

**Comment by pazguille** [comment]
@monsieurBelbo Estamos ordenando el repositorio de búsquedas. Esta sigue vigente?

**Comment by monsieurBelbo** [comment]
Ya no más. Lo cierro. ¡Gracias!
